
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
         
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: |
            Changes in this Release
            - first change
            - second change
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
